version: '3'

volumes:
    db_data:

services:
    mysql:
        image: mysql:5.7
        container_name: db_mysql
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: db_phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql:db
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        depends_on:
            - mysql

networks:
    default:
        external:
            name: backend