version: '3'

services:
    mailcatcher:
        image: schickling/mailcatcher:latest
        container_name: mailcatcher
        ports:
            - 9025:1025
            - 9080:1080

networks:
    default:
        external:
            name: backend
